Rent block
Prybluda/project-group-5 pull request #1
Opened 2023-07-27 18:50 UTC by MfD0

добавляє заголовок, картинку (PNG), форму

2023-07-28 09:45 UTC, AstafievaKateryna requested changes
я не знаю  чи буде при перевірці вважатись то помилкою, та в макеті ширина інпутів 335рх

2023-07-29 16:02 UTC, AstafievaKateryna reviewed
в класі rent-input-label має бути: font-size: 16px; letter-spacing: -0.72px
в класі rent-button для media screen and (min-width: 768px) height - 48px

2023-07-30 16:22 UTC, JaymesJoenes approved these changes

2023-07-30 17:02 UTC, JaymesJoenes approved these changes

2023-07-30 17:41 UTC, AstafievaKateryna approved these changes

2023-07-30 17:47 UTC, merged